In [1]:
!pip install numpy

In [2]:
import numpy as np 

In [3]:
Array1 = np.array([2,8,9]) 

print(Array1)

[2 8 9]


In [4]:
Array2= np.array([1,2,3,4,5,6,7,8])

print(Array2.shape) 

(8,)


In [5]:
Matris = Array2.reshape(2,4) 
print(Matris)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
print("shape: ",Matris.shape)

print("dimension: ",Matris.ndim) 

print("data type: ",Matris.dtype.name) 

print("size: ",Matris.size) 
                       
print("type",type(Matris)) 

shape:  (2, 4)
dimension:  2
data type:  int32
size:  8
type <class 'numpy.ndarray'>


In [7]:
ArrayThree= np.array([[2,4,6,8],[1,3,5,7],[9,10,11,12]])
print(ArrayThree)

[[ 2  4  6  8]
 [ 1  3  5  7]
 [ 9 10 11 12]]


In [8]:
print(ArrayThree.shape) 

(3, 4)


In [9]:
zeros= np.zeros((3,4))  
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.empty((4,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78019625e-306, 1.33511018e-306],
       [7.56599807e-307, 8.90104239e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.29062229e-306,
        1.42417222e-306, 1.33512648e-306],
       [7.56596412e-307, 1.37962185e-306, 1.78021798e-306,
        8.34451504e-308, 1.37954579e-306]])

In [12]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
Array3= np.linspace(0,10,20)
print(Array3)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [14]:
X= np.array([2,4,6])
Y= np.array([1,3,5]) 
print(X+Y) 
print(X-Y)
print(Y**2)

[ 3  7 11]
[1 1 1]
[ 1  9 25]


In [15]:
M= np.array([1,2,3,4,5,6,7])
print(M)

[1 2 3 4 5 6 7]


In [16]:
Liste = [1,2,3,4]

Liste_Array = np.array([5,6,7,8]) 
print(Liste_Array)
print(Liste)

[5 6 7 8]
[1, 2, 3, 4]


In [17]:
Array = np.array(Liste)
print(Array)

[1 2 3 4]


In [18]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [19]:
b=a

c=a

b[0]=5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [20]:
d = a.copy()
print(d)

[5 2 3]


In [21]:
a= np.array([1,2,3,4,5,6,7]) 
print(a[0])
print(a[0:4])

1
[1 2 3 4]


In [22]:
reverse_array = a[::-1] 
print(reverse_array)

[7 6 5 4 3 2 1]


In [24]:
Arrayw = np.array([[2,4,6],[1,3,5],[7,8,9]])
print(Arrayw)

[[2 4 6]
 [1 3 5]
 [7 8 9]]


In [25]:
array32 = np.array([[2,4],[1,3],[5,6]])
print(array32)

[[2 4]
 [1 3]
 [5 6]]


In [26]:
array32.resize((2,3)) 
print(array32)

[[2 4 1]
 [3 5 6]]
